export const THINKING_PHRASES = [
  "Thinking...",
  "Big brain activity",
  "Philosophizing",
  "Knowledge gathering",
  "Pondering the universe",
  "Consulting the digital oracle",
  "Crunching the numbers",
  "Reading the fine print",
  "Connecting the dots",
  "Channeling legal wisdom",
  "Brewing brilliance",
  "Summoning answers",
  "Parsing precedents",
  "Calculating cosmic truths",
  "Decoding the matrix",
  "Contemplating case law",
  "Mining for insights",
  "Assembling arguments",
  "Consulting the archives",
  "Synthesizing solutions",
  "Hold on, thinking hard",
  "Arguing with myself",
  "Considering counterarguments",
  "Taking a dramatic pause",
  "Asking myself tough questions",
  "Working smarter, not faster",
  "Channeling ancient wisdom",
  "Dusting off law books",
  "Calibrating legal compass",
  "Channeling inner Sherlock",
  "Omo Ologbon Doings",
];

export const DEFAULT_THINKING_INTERVAL = 5000;
