import type { Metadata, Viewport } from "next";
import { Comfortaa, Fraunces } from "next/font/google";
import "./globals.css";

import { QueryProvider } from "@/providers/QueryProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import { AttributionBootstrap } from "@/components/AttributionBootstrap";
import { PwaInstallProvider } from "@/components/pwa/PwaInstallProvider";

const comfortaa = Comfortaa({ subsets: ["latin"], variable: "--font-comfortaa" });
const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  axes: ["SOFT", "WONK", "opsz"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || "https://lawexa.com"),
  title: {
    default: "Lawexa - Where Modern Legal Work Happens",
    // Child routes export a bare title (e.g. "Terms of Service") and this
    // appends the brand → "Terms of Service | Lawexa". `default` is NOT run
    // through the template, so the homepage stays the line above. Routes
    // needing an exact title use `title.absolute`.
    template: "%s | Lawexa",
  },
  // @arthur's wording, 2026-08-11 — see `lib/constants/seo.ts` for why
  // "Nigerian" came out of every shared link.
  description:
    "Lawexa powers lawyers, students, and teams to research cases and laws across jurisdictions, draft, study, and collaborate with AI to get legal work done faster and reliably",
  // The web app manifest is generated by `app/manifest.ts` and auto-linked by
  // Next at /manifest.webmanifest — do NOT also declare `manifest` here (that
  // pointed at the stale, duplicate /site.webmanifest and produced two links).
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.png", type: "image/png", sizes: "32x32" },
    ],
    apple: "/apple-icon.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Lawexa",
  },
  openGraph: {
    type: "website",
    siteName: "Lawexa",
    locale: "en_NG",
  },
  twitter: {
    card: "summary_large_image",
    site: "@LawexaAi",
  },
};

export const viewport: Viewport = {
  themeColor: "#C9A227",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${comfortaa.variable} ${fraunces.variable}`} suppressHydrationWarning>
      <body className="min-h-screen bg-background font-sans antialiased" suppressHydrationWarning>
        <ThemeProvider>
          <QueryProvider>
            <AttributionBootstrap />
            <PwaInstallProvider />
            {children}
            <Toaster position="top-right" />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
